name: Bug Report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: checks
    attributes:
      label: Preliminary Checks
      description: Please check the following before submitting a bug report.
      options:
        - label: I have checked that a similar issue does not already exist
          required: true
        - label: I am using the latest version of the integration
          required: true
  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      placeholder: 2025.2.0
    validations:
      required: true
  - type: input
    id: integration_version
    attributes:
      label: Oblamatik Integration Version
      placeholder: v2.1.25
    validations:
      required: true
  - type: dropdown
    id: device_model
    attributes:
      label: Device Model
      options:
        - KWC
        - Viega Multiplex Trio E
        - Crosswater
        - Other (please describe in details)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Diagnostic Logs
      description: |
        Please paste logs from Home Assistant (Settings -> System -> Logs).
        Enable debug logging for the integration if possible:
        ```yaml
        logger:
          default: info
          logs:
            custom_components.oblamatik: debug
        ```
      render: shell
