name: Propozycja funkcji
description: Zasugeruj pomysł na ten projekt
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Dziękujemy za zasugerowanie pomysłu! Proszę wypełnić poniższy formularz.
  - type: textarea
    id: problem
    attributes:
      label: Czy Twoja propozycja jest związana z problemem?
      description: Jasny i zwięzły opis problemu. Np. "Zawsze denerwuje mnie, gdy..."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Opisz rozwiązanie, które chciałbyś zobaczyć
      description: Jasny i zwięzły opis tego, co ma się stać.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Opisz alternatywy, które rozważyłeś
      description: Jasny i zwięzły opis wszelkich alternatywnych rozwiązań lub funkcji, które brałeś pod uwagę.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Dodatkowy kontekst
      description: Dodaj tutaj wszelkie inne konteksty lub zrzuty ekranu dotyczące prośby o funkcję.
    validations:
      required: false
